# Generated by Django 3.1.5 on 2021-02-01 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('additionalnotes', models.TextField(default='Blank')),
                ('dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('option_one', models.CharField(default='Blank', max_length=30)),
                ('option_two', models.CharField(default='Blank', max_length=30)),
                ('option_three', models.CharField(default='Blank', max_length=30)),
                ('option_four', models.CharField(default='Blank', max_length=30)),
                ('option_five', models.CharField(default='Blank', max_length=30)),
                ('option_one_count', models.IntegerField(default=0)),
                ('option_two_count', models.IntegerField(default=0)),
                ('option_three_count', models.IntegerField(default=0)),
                ('option_four_count', models.IntegerField(default=0)),
                ('option_five_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='poll.poll')),
            ],
        ),
    ]
