# Generated by Django 3.1.5 on 2021-02-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='website',
            field=models.URLField(blank=True, default='None'),
        ),
    ]
