# Generated by Django 3.1.5 on 2021-02-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_remove_poll_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='note',
        ),
    ]
