# Generated by Django 3.1.5 on 2021-02-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20210202_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='EmailAddress',
        ),
    ]
