# Generated by Django 3.1.5 on 2021-02-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20210202_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='EmailAddress',
            new_name='email',
        ),
    ]
