# Generated by Django 3.1.5 on 2021-02-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20210202_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='additionalnotes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_five',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_four',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_one',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_three',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_two',
            field=models.CharField(default='', max_length=30),
        ),
    ]
