# Generated by Django 3.1.5 on 2021-02-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20210203_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='AreYouVoting',
            field=models.CharField(default='', max_length=255),
        ),
    ]
